branch-defaults:
  default:
    environment: udac-cloudDev-imageFilter
    group_suffix: null
  dev:
    environment: udac-cloudDev-imageFilter
  master:
    environment: udac-cloudDev-imageFilter
deploy:
  artifact: ./www/Archive.zip
global:
  application_name: udac-cloudDev-imageFilter
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
